# https://uiua.org/pad?src=0_18_0-dev_3__eJxLUQCBR20TFNTSihKLFZRSEisN9UoqSpS4UuFSKgo-ZhZcYK6CAohnbIDECzJBkTNFljJDVuhjiiznY4jMsbRE1mZogixnYcQVkFhUnAp2y-k5Go965zyatlfh0HrNR10zNR71dj6auRbC7Fx4aMOjaQs1YYxHvbM0HnVPfdQ2Q8FQ89H8OSC-rYPPo7aZhpqnZ2o86poDUtS5wCEmTxNkR8mjpkawLfraj3qmGsRoPJq-39DAQFvzUVeTqQFURRNUha0BRDZG-zTIPYc2HJ6OrKxRAeLoFLg2GB8AvxyCJg==

d     ← &fras "./days/day1.txt"
e     ← $ L68
        $ L30
        $ R48
        $ L5
        $ R60
        $ L55
        $ L1
        $ L99
        $ R14
        $ L82
Parse ← ˜(⍜▽ ¯)⊙(⍉♭)⊙(≡°□)≡°□⍚(⋕↘ 1)⟜⍚(=@L↙1)˙(⊜□≠@\n)
Part₁ ← /+⌕0\(◿100+)⊂50
Part₂ ← /+=0◿100\+˜▽°×⊂50
Part₁ Parse d
Part₂ Parse d
